import java.io.InputStream;
import java.util.Scanner;
import java.math.BigInteger; 
import java.security.MessageDigest; 
import java.security.NoSuchAlgorithmException; 
class SHA { 
    public static String getSHA(String input) 
    { 
  
        try { 
            MessageDigest md = MessageDigest.getInstance("SHA-512"); 
            byte[] messageDigest = md.digest(input.getBytes());  
            BigInteger no = new BigInteger(1, messageDigest);  
            String hashtext = no.toString(16); 
  
            while (hashtext.length() < 32) {
                hashtext = "0" + hashtext; 
            } 
  
            return hashtext; 
        } 
        catch (NoSuchAlgorithmException e) { 
            System.out.println("Exception thrown" + " for incorrect algorithm: " + e); 
  	    return null; 
        } 
    }  
    public static void main(String args[]) throws NoSuchAlgorithmException 
    { 
        System.out.println("HashCode Generated by SHA-512 for:");
	Scanner scanner = new Scanner( System.in );
	System.out.print( "Type some data for the program to generate Hash Value: " );
	String input = scanner.nextLine();
	System.out.println( "Hash = " + getSHA(input)); 
    } 
} 
